### ISSUE TITLE
Import path does not begin with hostname?

### ISSUE THREAD

**Issue by mhabicht** [LINBIT/drbdtop#10]
I will not list all, but here is one. I have not had this happen before when I used GO.

'# env
GOPATH=/root/go

:~/go# go get github.com/LINBIT/drbdtop
package fmt: unrecognized import path "fmt" (import path does not begin with hostname)

What do I need to add?

**Comment by haySwim** [comment]
This appears to be a go issue unrelated to drbdtop, so I'll just direct you here:
https://stackoverflow.com/questions/20458796/unrecognized-import-path-with-go-get
