### ISSUE TITLE
Bogus "sha1" resource

### ISSUE THREAD

**Issue by elonen** [LINBIT/drbdtop#11]
On one of my LINSTOR cluster nodes, drbdtop shows a non-existing resource "sha1" with no nodes. It only shows up in drbdtop listing, not in `/dev/drbd/by-res`, `drbd-overview` or `/var/lib/linstor.d/`.

```
DRBDTOP v0.2.1-3-g70075d0 (kernel: v9.0.16/utils: v9.5.0)
...
│  sha1                 | Secondary | ✓     | ✓          | ✓           | ✓       | ✓
```

```
DRBDTOP v0.2.1-3-g70075d0 (kernel: v9.0.16/utils: v9.5.0) - Details for sha1
┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│Resource: sha1: (Overall danger score: 0)                                                                                                                           │
│ Local Disc(Secondary):                                                                                                                                             │
│                                                                                                                                                                    │
│
```

**Comment by haySwim** [comment]
That's really interesting! 

Could you provide me with the output of `drbdsetup events2 --now --verbose --statistics` on that machine? 

There's also a `/etc/drbd.d` directory that might be of interest to us here. 
________________________________

**Comment by elonen** [comment]
Ok, there it is in drbdsetup output:
```
exists peer-device name:vm-103-disk-1 peer-node-id:1 conn-name:mox-a volume:0 replication:Established peer-disk:UpToDate peer-client:no resync-suspended:no received:1
087504 sent:0 out-of-sync:0 pending:0 unacked:0
exists peer-device name:vm-103-disk-1 peer-node-id:0 conn-name:mox-b volume:0 replication:Established peer-disk:UpToDate peer-client:no resync-suspended:no received:8
48 sent:0 out-of-sync:0 pending:0 unacked:0
exists resource name:sha1 role:Secondary suspended:no write-ordering:none
exists resource name:vm-104-disk-1 role:Secondary suspended:no write-ordering:flush
exists connection name:vm-104-disk-1 peer-node-id:0 conn-name:mox-a connection:Connected role:Secondary congested:no ap-in-flight:0 rs-in-flight:0
exists connection name:vm-104-disk-1 peer-node-id:1 conn-name:mox-b connection:Connected role:Secondary congested:no ap-in-flight:0 rs-in-flight:0
```

Not present in `/etc/drbd.d`.

**Comment by rck** [comment]
Did that resource ever exist? Like did you create it with `linstor` at one point? `drbdsetup status sha1` would also be interesting.

**Comment by elonen** [comment]
No, never explicitly created a resource names `sha1`. My best guess is a misplaced command argument somewhere in the chain (I'm using LINSTOR Proxmox plugin and doing manual maintenance on drbdadmn level, so there are a lot of layers where this might have happened).

The resource only shows up on one node, and status report is rather short:
```
# drbdsetup status sha1
sha1 role:Secondary
```

**Comment by rck** [comment]
Hm, all in all most likely not a bug in `drbdtop`. It is strange that it matches an actual value that is set in the res files LINSTOR creates. AFAIR it sets `cram-hmac-alg     sha1;`.  To produce such a state as yours, a `drbdsetup new-resource sha1 0` is enough, but who/and why would that have been executed?

Any other hints for that? Syslogs? Proxmox logs? Shell history? If you just want to get rid of it, you can issue a `drbdsetup down sha1`. Then it would be interesting if `drbdadm up sha1` regenerates it. I assume it does not, because then there needs to be a res file and we have to find it :)

**Comment by elonen** [comment]
Reboot and/or package upgrade seems to have exorcised it, and `drbdadm up sha1` doesn't bring it back on any node. Guess we'll never know. :)
