### ISSUE TITLE
Feature request: Show node name on UI

### ISSUE THREAD

**Issue by elonen** [LINBIT/drbdtop#8]
When performing actions with drbdtop (especially dangerous ones), I often need to double check that I'm on the correct host. Currently you have to exit the program to check command prompt (or uname or somethin). It would be nice if the UI would show current node name, for example in the right top corner.

**Comment by rck** [comment]
I'm not a big fan of that, IMO such information should be part of the tmux window you are in or something like that. I mean `htop` also does not display the hostname and you can kill processes with it.

Anyways, it is trivial and we have space in the header, so here we go.
