### ISSUE TITLE
Feature request: explain resource's danger score on "detailed status"

### ISSUE THREAD

**Issue by elonen** [LINBIT/drbdtop#9]
Would it be possible to explain what the danger score consists of for a particular resource in its detailed status page? This would help debug issues.

**Comment by haySwim** [comment]
The detailed status should display anything that's potentially troubling in red. 

The danger score was originally meant to be internal sorting magic and the detailed status page was supposed to be enough to (at least begin to) determine what the issue might be.

A lot of the scoring is pretty much flat, so it's not different than red or green. The only thing that scales is out of sync blocks and that's by the log of out of sync KiB, so basically off or on too, but allows for bigger resources that are greatly out of sync to sort up to the top.
